import { Metadata } from "next";
import NavBar from "../components/NavBar";
import Header from "./components/Header";
import RestaurantCard from "./components/Restaurant";
import SideBar from "./components/SideBar";

export const metadata: Metadata = {
  title: '| search',
  description: 'Generated by create next app',
  keywords: ["search", "restaurant"]
}

export default function SearchPage() {
  return (
    <>
      <Header />
      <div className="flex py-4 m-auto w-2/3 justify-between items-start">
        <SideBar />
        <div className="w-5/6">
          <RestaurantCard />
        </div>
      </div>
    </>
  )
}